- name: register ruby version
  shell: |
    #!/usr/bin/env bash
    set -euo pipefail
    source {{asdf_root_dir}}/current/asdf.sh
    cd {{app_dir}}
    asdf current ruby | awk '{print $2}'
  args:
    chdir: "{{app_dir}}"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{app_user}}"
  become_method: sudo
  register: ruby_version

- name: install config
  template:
    src: '{{config_file}}'
    dest: '{{app_dir}}/config.yml'
    mode: 0600
    owner: '{{app_user}}'
    group: '{{app_user}}'

- name: copy {{app_name}}.service
  template:
    src: 'aad-leihs-auth.service'
    dest: /etc/systemd/system/{{app_name}}.service
    mode: 0644

- name: restart {{app_name}}.service
  service:
    name: '{{app_name}}.service'
    state: restarted
    daemon_reload: yes
    enabled: yes
