- name: install config template
  template: 
    src: config.yml
    dest: '{{app_dir}}/config.yml'
    mode: 0600
    owner: '{{app_user}}'
    group: '{{app_user}}'

- name: copy {{app_name}}.service
  template:
    src: '{{app_name}}.service'
    dest: /etc/systemd/system/{{app_name}}.service
    mode: 0644
 
- name: reload systemctl
  command: systemctl daemon-reload
  changed_when: false

- name: restart {{app_name}}.service
  service:
    name: '{{app_name}}.service'
    state: restarted
    enabled: yes

- name: wait for {{app_name}}.service
  wait_for:
    host: localhost
    port: '{{adl_port}}'
    timeout: 60
