- name: register ruby version
  shell: |
    #!/usr/bin/env bash
    set -euo pipefail
    source {{asdf_root_dir}}/current/asdf.sh
    cd {{app_dir}}
    asdf current ruby | awk '{print $2}'
  args:
    chdir: "{{app_dir}}"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{app_user}}"
  become_method: sudo
  register: ruby_version

- name: make sure `/etc/leihs/' exists
  file:
    path: /etc/leihs
    state: directory
    mode: '0755'

- name: install config
  template:
    src: '{{config_file}}'
    dest: '/etc/leihs/{{app_name}}.yml'
    mode: '0640'
    owner: root
    group: '{{app_user}}'

- name: copy service file
  template:
    src: 'leihs-aad-auth.service'
    dest: /etc/systemd/system/{{app_name}}.service
    mode: 0644

- name: restart {{app_name}}.service
  service:
    name: '{{app_name}}.service'
    state: restarted
    daemon_reload: yes
    enabled: yes
